apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 99-enable-iommu-pass-through
spec:
  kernelArguments:
    - "iommu=pt"      # This enables IOMMU Pass-Through Mode