apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mikrotik-nvme
provisioner: org.democratic-csi.node-manual
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: false