apiVersion: v1
kind: PersistentVolume
metadata:
  name: mikrotik-vm-storage-001
spec:
  capacity:
    storage: 1Ti

  accessModes:
    - ReadWriteOnce

  persistentVolumeReclaimPolicy: Retain

  storageClassName: mikrotik-nvme

  volumeMode: Block

  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    volumeHandle: mikrotik-rds2216-vm-storage-001

    volumeAttributes:
      transport: "tcp://172.16.100.125:4420"
      nqn: "nqn.2026-09.com.mikrotik:rds2216.vm-storage-001"
      nsid: "1"
      node_attach_driver: "nvmeof"
      provisioner_driver: "node-manual"