apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 99-core-password
  labels:
    machineconfiguration.openshift.io/role: master
spec:
  config:
    ignition:
      version: 3.2.0
    passwd:
      users:
        - name: core
          passwordHash: $6$/dAWtZhNOiMPG5ms$fBKEHAxjJSWeH/Z1ZLmtABgLR9kUNJopISY.9FOdVJMi.BJh8D9wXu9zEx/93bxQMluJdSEDdkqsLRultbaRX1