apiVersion: mellanox.com/v1alpha1
kind: MacvlanNetwork
metadata:
  name: rdma-bond
spec:
  networkNamespace: rdma-test
  master: bond1
  mode: bridge
  mtu: 9000
  ipam: |
    {
      "type": "whereabouts",
      "range": "172.16.101.0/24",
      "exclude": [
        "172.16.101.0/30",
        "172.16.101.255/32"
      ]
    }