apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: set-lacp-bond-jumbo-frames-min
spec:
  nodeSelector:
    kubernetes.io/os: linux
  desiredState:
    interfaces:
      # 1. Update first slave interface MTU only
      - name: enp1s0f0np0
        type: ethernet
        state: up
        mtu: 9100
      # 2. Update second slave interface MTU only
      - name: enp1s0f1np1
        type: ethernet
        state: up
        mtu: 9100
      # 3. Update the existing bond0 MTU only
      - name: bond0
        type: bond
        state: up
        mtu: 9100