apiVersion: v1
kind: Service
metadata:
  name: svc-postgres-clusterip
  namespace: percap
spec:
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  selector:
    internalService: svc-postgres-clusterip
  type: ClusterIP