name: Embed code in README

on:
  pull_request:
    branches:
      - main
workflow_dispatch:

jobs:
  embed-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.4.0
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
          ref: refs/heads/${{ github.head_ref }}

      - uses: tokusumi/markdown-embed-code@main
        with:
          markdown: "Performance/IOMMU/IOMMU.md"
          token: ${{ secrets.GITHUB_TOKEN }}
          message: "Synchronizing Readme"
          silent: true
