name: Embed code in README

on:
  pull_request:
    paths:
      - ".github/workflows/update-readme.yml"
      - "Performance/IOMMU/IOMMU.md"
  push:
    branches: [ main ]
    paths:
      - "Performance/IOMMU/IOMMU.md"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # only needed if you commit back to repo

    steps:
      - uses: actions/checkout@main
#        with:
#          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
#          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
#          ref: refs/heads/${{ github.head_ref }}

      - uses: singlecheeze/markdown-embed-code@main
        with:
          markdown: "Performance/IOMMU/IOMMU.md"
          token: ${{ secrets.GITHUB_TOKEN }}
          message: "Synchronizing Readme"
#          silent: true
